# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

GET http://127.0.0.1:8000/currency-quote/all
Accept: application/json


###

GET http://127.0.0.1:8000/currency-quote/USD
Accept: application/json


###

GET http://127.0.0.1:8000/currency-quote/30days/USD
Accept: application/json


###

GET http://127.0.0.1:8000/currency-quote/30days/plot/USD
Accept: application/json

###

GET http://127.0.0.1:8000/weather-forecast
Accept: application/json
